cluster:
  cpu_cores: 32
  # 1024 * 70
  ram_memory: 71680
  disk_count: 2
  virt_bundles: ['odf', 'cnv', 'lso', 'nmstate']

oracle:
  # web server to download all oracle packages and images
  web_server: http://10.9.76.8:8888
  # images OL8U10_x86_64-kvm-b258.qcow2 (from oracle or rhels)
  rac_image: rhel-guest-image-8.10-1362.x86_64.qcow2
  disk_bus: virtio
  # thread io supported on ocp 4.19 and virtio bus
  enabled_thread_io: False
  thread_count: 2
  # virtio bus rac_disks are ["vdc","vdd","vde"]
  # scsi bus rac_disks are ["sdb","sdc","sdd"]
  rac_disks: ["vdc", "vdd", "vde"]
